# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ai_inference_pb2 as ai__inference__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ai_inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class AIInferenceStub(object):
    """─── Service Definition ────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeSentiment = channel.unary_unary(
                '/ai_inference.AIInference/AnalyzeSentiment',
                request_serializer=ai__inference__pb2.SentimentRequest.SerializeToString,
                response_deserializer=ai__inference__pb2.SentimentResponse.FromString,
                _registered_method=True)
        self.GenerateText = channel.unary_stream(
                '/ai_inference.AIInference/GenerateText',
                request_serializer=ai__inference__pb2.GenerateRequest.SerializeToString,
                response_deserializer=ai__inference__pb2.GenerateChunk.FromString,
                _registered_method=True)
        self.SummarizeDocument = channel.stream_unary(
                '/ai_inference.AIInference/SummarizeDocument',
                request_serializer=ai__inference__pb2.TextChunk.SerializeToString,
                response_deserializer=ai__inference__pb2.SummaryResponse.FromString,
                _registered_method=True)
        self.LiveChat = channel.stream_stream(
                '/ai_inference.AIInference/LiveChat',
                request_serializer=ai__inference__pb2.ChatMessage.SerializeToString,
                response_deserializer=ai__inference__pb2.ChatMessage.FromString,
                _registered_method=True)


class AIInferenceServicer(object):
    """─── Service Definition ────────────────────────────────────────────────────

    """

    def AnalyzeSentiment(self, request, context):
        """– Unary: send one text, get one sentiment result
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateText(self, request, context):
        """– Server-streaming: send one prompt, get a stream of tokens
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SummarizeDocument(self, request_iterator, context):
        """– Client-streaming: send many text chunks, get one summary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LiveChat(self, request_iterator, context):
        """– Bidirectional-streaming: live chat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeSentiment': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeSentiment,
                    request_deserializer=ai__inference__pb2.SentimentRequest.FromString,
                    response_serializer=ai__inference__pb2.SentimentResponse.SerializeToString,
            ),
            'GenerateText': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateText,
                    request_deserializer=ai__inference__pb2.GenerateRequest.FromString,
                    response_serializer=ai__inference__pb2.GenerateChunk.SerializeToString,
            ),
            'SummarizeDocument': grpc.stream_unary_rpc_method_handler(
                    servicer.SummarizeDocument,
                    request_deserializer=ai__inference__pb2.TextChunk.FromString,
                    response_serializer=ai__inference__pb2.SummaryResponse.SerializeToString,
            ),
            'LiveChat': grpc.stream_stream_rpc_method_handler(
                    servicer.LiveChat,
                    request_deserializer=ai__inference__pb2.ChatMessage.FromString,
                    response_serializer=ai__inference__pb2.ChatMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_inference.AIInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_inference.AIInference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIInference(object):
    """─── Service Definition ────────────────────────────────────────────────────

    """

    @staticmethod
    def AnalyzeSentiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_inference.AIInference/AnalyzeSentiment',
            ai__inference__pb2.SentimentRequest.SerializeToString,
            ai__inference__pb2.SentimentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai_inference.AIInference/GenerateText',
            ai__inference__pb2.GenerateRequest.SerializeToString,
            ai__inference__pb2.GenerateChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SummarizeDocument(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/ai_inference.AIInference/SummarizeDocument',
            ai__inference__pb2.TextChunk.SerializeToString,
            ai__inference__pb2.SummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LiveChat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ai_inference.AIInference/LiveChat',
            ai__inference__pb2.ChatMessage.SerializeToString,
            ai__inference__pb2.ChatMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
