# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai_inference.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61i_inference.proto\x12\x0c\x61i_inference\" \n\x10SentimentRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"6\n\x11SentimentResponse\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\"!\n\x0fGenerateRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"\x1e\n\rGenerateChunk\x12\r\n\x05token\x18\x01 \x01(\t\"\x1c\n\tTextChunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"\"\n\x0fSummaryResponse\x12\x0f\n\x07summary\x18\x01 \x01(\t\",\n\x0b\x43hatMessage\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t2\xc5\x02\n\x0b\x41IInference\x12S\n\x10\x41nalyzeSentiment\x12\x1e.ai_inference.SentimentRequest\x1a\x1f.ai_inference.SentimentResponse\x12L\n\x0cGenerateText\x12\x1d.ai_inference.GenerateRequest\x1a\x1b.ai_inference.GenerateChunk0\x01\x12M\n\x11SummarizeDocument\x12\x17.ai_inference.TextChunk\x1a\x1d.ai_inference.SummaryResponse(\x01\x12\x44\n\x08LiveChat\x12\x19.ai_inference.ChatMessage\x1a\x19.ai_inference.ChatMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENTIMENTREQUEST']._serialized_start=36
  _globals['_SENTIMENTREQUEST']._serialized_end=68
  _globals['_SENTIMENTRESPONSE']._serialized_start=70
  _globals['_SENTIMENTRESPONSE']._serialized_end=124
  _globals['_GENERATEREQUEST']._serialized_start=126
  _globals['_GENERATEREQUEST']._serialized_end=159
  _globals['_GENERATECHUNK']._serialized_start=161
  _globals['_GENERATECHUNK']._serialized_end=191
  _globals['_TEXTCHUNK']._serialized_start=193
  _globals['_TEXTCHUNK']._serialized_end=221
  _globals['_SUMMARYRESPONSE']._serialized_start=223
  _globals['_SUMMARYRESPONSE']._serialized_end=257
  _globals['_CHATMESSAGE']._serialized_start=259
  _globals['_CHATMESSAGE']._serialized_end=303
  _globals['_AIINFERENCE']._serialized_start=306
  _globals['_AIINFERENCE']._serialized_end=631
# @@protoc_insertion_point(module_scope)
