# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai_inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61i_inference.proto\x12\x02\x61i\" \n\x10SentimentRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"6\n\x11SentimentResponse\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\"#\n\x11GenerationRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"\x1e\n\rTokenResponse\x12\r\n\x05token\x18\x01 \x01(\t\"\x1a\n\tTextChunk\x12\r\n\x05\x63hunk\x18\x01 \x01(\t\"\"\n\x0fSummaryResponse\x12\x0f\n\x07summary\x18\x01 \x01(\t\",\n\x0b\x43hatMessage\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t2\xf3\x01\n\x0b\x41IInference\x12?\n\x10\x41nalyzeSentiment\x12\x14.ai.SentimentRequest\x1a\x15.ai.SentimentResponse\x12<\n\x0eGenerateStream\x12\x15.ai.GenerationRequest\x1a\x11.ai.TokenResponse0\x01\x12\x37\n\x0fSummarizeStream\x12\r.ai.TextChunk\x1a\x13.ai.SummaryResponse(\x01\x12,\n\x04\x43hat\x12\x0f.ai.ChatMessage\x1a\x0f.ai.ChatMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENTIMENTREQUEST']._serialized_start=26
  _globals['_SENTIMENTREQUEST']._serialized_end=58
  _globals['_SENTIMENTRESPONSE']._serialized_start=60
  _globals['_SENTIMENTRESPONSE']._serialized_end=114
  _globals['_GENERATIONREQUEST']._serialized_start=116
  _globals['_GENERATIONREQUEST']._serialized_end=151
  _globals['_TOKENRESPONSE']._serialized_start=153
  _globals['_TOKENRESPONSE']._serialized_end=183
  _globals['_TEXTCHUNK']._serialized_start=185
  _globals['_TEXTCHUNK']._serialized_end=211
  _globals['_SUMMARYRESPONSE']._serialized_start=213
  _globals['_SUMMARYRESPONSE']._serialized_end=247
  _globals['_CHATMESSAGE']._serialized_start=249
  _globals['_CHATMESSAGE']._serialized_end=293
  _globals['_AIINFERENCE']._serialized_start=296
  _globals['_AIINFERENCE']._serialized_end=539
# @@protoc_insertion_point(module_scope)
