services:
  grpc-server:
    build: ./server
    container_name: grpc-server
    ports:
      - "50051:50051"

  nginx:
    image: nginx:latest
    ports:
      - "5000:5000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - grpc-server