events {}

http {
    upstream grpc_backend {
        server grpc-server:50051;
    }

    server {
        listen 5000 http2;

        location / {
            grpc_pass grpc://grpc_backend;
        }
    }
}